INSERT INTO region(nombre_re)
VALUES('REGION BRUNCA');

INSERT INTO region(nombre_re)
VALUES('REGION CENTRAL NORTE');

INSERT INTO region(nombre_re)
VALUES('REGION CENTRAL SUR');

INSERT INTO region(nombre_re)
VALUES('REGION CHOROTEGA');

INSERT INTO region(nombre_re)
VALUES('REGION HUETAR ATLANTICA');

INSERT INTO region(nombre_re)
VALUES('REGION HUETAR NORTE');

INSERT INTO region(nombre_re)
VALUES('REGION PACIFICO CENTRAL');