USE [Proyecto]
GO

create table as_region(
  codigo_as int,
  codigo_region int
);


INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (1, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (2, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (3, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (4, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (5, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (6, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (7, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (8, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (9, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (10, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (11, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (12, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (13, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (14, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (15, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (16, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (17, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (18, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (19, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (20, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (22, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (23, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (24, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (25, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (26, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (27, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (28, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (29, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (30, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (31, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (32, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (33, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (34, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (35, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (36, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (37, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (38, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (39, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (40, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (41, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (42, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (43, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (44, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (45, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (46, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (47, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (48, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (49, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (50, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (51, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (52, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (53, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (54, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (55, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (56, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (57, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (58, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (59, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (60, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (61, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (62, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (63, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (64, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (65, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (66, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (67, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (68, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (69, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (70, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (71, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (72, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (73, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (74, 5);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (75, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (76, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (77, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (78, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (79, 4);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (80, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (81, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (82, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (83, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (84, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (85, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (86, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (87, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (88, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (89, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (90, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (91, 7);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (92, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (93, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (94, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (95, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (96, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (97, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (98, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (99, 3);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (100, 6);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (101, 1);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (102, 2);

INSERT INTO AS_REGION (CODIGO_AS, CODIGO_REGION) 
VALUES (103, 2);

select * from as_region;